version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: regulation_task/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: always

  frontend:
    build:
      context: ./frontend_task/colab_frontend
    ports:
      - "3000:3000"
    restart: always
